[package]
name = "clickhouse-sink"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clickhouse = "0.13.1"
fluvio = "0.24.1"
futures-lite = "2.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }